name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Check out code
      uses: actions/checkout@v2

    - name: Download module dependencies
      env: 
         GOPROXY: "https://proxy.golang.org"
      run: go mod download
    
    - name: Run compose
      run: APP_PROJECT=protokaf docker-compose -f build/docker/docker-compose.yaml up -d

    - name: Test
      run: go test -v -coverprofile=coverage.txt ./...
